proxy:
  secretToken: "CHANGEME_SECRET_TOKEN"
  service:
    type: NodePort

hub:
  config:
    Authenticator:
      admin_users:
        - imane
    DummyAuthenticator:
      enabled: true
      password: "password"

singleuser:
  image:
    name: jupyter/minimal-notebook
    tag: latest
